[project]
name = "aegis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.6",
    "openai>=1.109.1",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "pyclean>=3.1.0",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]
